export interface DiseaseInfo {
  diseaseKey: string;
  diseaseName: string;
  cropName: string;
  category: string;
  severity: string;
  overview: string;
  symptoms: string[];
  causes: string[];
  conditions: string[];
  prevention: string[];
  management: string[];
  suggestedActions: string[];
  isHealthy: boolean;
}

export const DISEASE_DATABASE: DiseaseInfo[] = [
  {
    diseaseKey: "Tomato___healthy",
    diseaseName: "Healthy",
    cropName: "Tomato",
    category: "Healthy",
    severity: "none",
    overview: "The plant shows no signs of disease. Leaves are green, healthy, and free from visible symptoms of infection or nutrient deficiency.",
    symptoms: ["Green, vibrant leaves", "Normal leaf shape and size", "No visible spots or lesions", "Healthy stem structure"],
    causes: [],
    conditions: [],
    prevention: ["Maintain regular watering schedule", "Ensure proper nutrition", "Monitor for early signs of disease", "Practice crop rotation"],
    management: ["Continue current care practices", "Regular monitoring"],
    suggestedActions: ["Continue monitoring regularly", "Maintain current agricultural practices"],
    isHealthy: true,
  },
  {
    diseaseKey: "Tomato___Early_blight",
    diseaseName: "Early Blight",
    cropName: "Tomato",
    category: "Fungal",
    severity: "moderate",
    overview: "Early blight is caused by the fungus Alternaria solani. It is one of the most common tomato diseases, affecting leaves, stems, and fruits. The disease typically starts on older leaves and progresses upward.",
    symptoms: ["Dark brown to black concentric rings on leaves (target-like spots)", "Yellowing around spots", "Lower leaves affected first", "Spots may merge causing large dead areas", "Stem lesions near soil line"],
    causes: ["Alternaria solani fungus", "Infected plant debris", "Wind-blown or water-splashed spores", "Contaminated seeds"],
    conditions: ["Warm temperatures (24-29°C)", "High humidity", "Prolonged leaf wetness", "Poor air circulation", "Stressed or weakened plants"],
    prevention: ["Use disease-free seeds and transplants", "Practice crop rotation (2-3 year cycle)", "Remove and destroy infected plant debris", "Ensure adequate plant spacing", "Mulch around plants to reduce soil splash"],
    management: ["Remove infected leaves immediately", "Apply appropriate fungicide if severe", "Improve air circulation", "Avoid overhead irrigation", "Ensure balanced fertilization"],
    suggestedActions: ["Remove and destroy affected lower leaves", "Improve spacing between plants", "Apply mulch to prevent soil splash", "Consider fungicide application", "Monitor nearby plants for spread"],
    isHealthy: false,
  },
  {
    diseaseKey: "Tomato___Late_blight",
    diseaseName: "Late Blight",
    cropName: "Tomato",
    category: "Fungal",
    severity: "high",
    overview: "Late blight is caused by Phytophthora infestans, the same pathogen that caused the Irish Potato Famine. It can destroy entire crops rapidly under favorable conditions.",
    symptoms: ["Water-soaked lesions on leaves", "White fuzzy growth on leaf undersides", "Dark brown to black spots", "Rapid leaf death", "Firm, dark lesions on fruits"],
    causes: ["Phytophthora infestans oomycete", "Infected potato or tomato plant material", "Wind-dispersed spores", "Contaminated transplants"],
    conditions: ["Cool temperatures (15-25°C)", "High humidity above 90%", "Prolonged wet conditions", "Dew formation", "Overcast weather"],
    prevention: ["Use resistant varieties when available", "Destroy volunteer potato and tomato plants", "Ensure good air circulation", "Avoid overhead irrigation", "Monitor weather forecasts for disease-favorable conditions"],
    management: ["Remove and destroy all infected plants immediately", "Apply fungicide preventively during favorable conditions", "Harvest healthy fruit promptly", "Do not compost infected material"],
    suggestedActions: ["Immediately remove and destroy infected plant material", "Apply fungicide to surrounding plants", "Improve drainage and air circulation", "Consult an agricultural extension service", "Monitor all nearby plants closely"],
    isHealthy: false,
  },
  {
    diseaseKey: "Tomato___Leaf_Mold",
    diseaseName: "Leaf Mold",
    cropName: "Tomato",
    category: "Fungal",
    severity: "moderate",
    overview: "Leaf mold is caused by the fungus Passalora fulva (formerly Cladosporium fulvum). It primarily affects greenhouse-grown tomatoes but can occur in field production under humid conditions.",
    symptoms: ["Pale green to yellow spots on upper leaf surface", "Olive-green to brown velvety mold on lower leaf surface", "Leaves may curl and dry", "Primarily affects older leaves"],
    causes: ["Passalora fulva fungus", "Infected plant debris", "Airborne spores", "Contaminated equipment"],
    conditions: ["High humidity above 85%", "Poor air circulation", "Moderate temperatures (20-25°C)", "Greenhouse environments", "Dense canopy"],
    prevention: ["Improve greenhouse ventilation", "Use resistant varieties", "Maintain lower humidity", "Avoid leaf wetness", "Proper plant spacing"],
    management: ["Remove affected leaves", "Increase air circulation", "Reduce humidity", "Apply fungicide if necessary", "Sanitize greenhouse between crops"],
    suggestedActions: ["Improve ventilation around plants", "Remove affected leaves carefully", "Reduce humidity if in greenhouse", "Monitor for spread to other plants", "Consider resistant varieties for next planting"],
    isHealthy: false,
  },
  {
    diseaseKey: "Tomato___Septoria_leaf_spot",
    diseaseName: "Septoria Leaf Spot",
    cropName: "Tomato",
    category: "Fungal",
    severity: "moderate",
    overview: "Septoria leaf spot is caused by the fungus Septoria lycopersici. It is one of the most common tomato foliage diseases and can cause significant defoliation.",
    symptoms: ["Small circular spots with dark borders and gray centers", "Tiny black dots (pycnidia) in center of spots", "Yellowing of leaves", "Starting on lower leaves, progressing upward", "Premature leaf drop"],
    causes: ["Septoria lycopersici fungus", "Infected crop debris", "Rain splash dispersal", "Contaminated tools and equipment", "Infected volunteer plants"],
    conditions: ["Warm, wet weather", "Rainy periods", "High humidity", "Overhead irrigation", "Temperatures 20-25°C"],
    prevention: ["Practice crop rotation", "Remove plant debris after harvest", "Use disease-free transplants", "Avoid overhead watering", "Stake plants for better air flow"],
    management: ["Remove infected leaves at first sign", "Apply mulch to reduce splash", "Apply fungicide if widespread", "Improve air circulation", "Water at base of plants"],
    suggestedActions: ["Remove and destroy affected lower leaves", "Apply organic mulch around plants", "Switch to drip irrigation if possible", "Apply copper-based fungicide", "Monitor for continued spread"],
    isHealthy: false,
  },
  {
    diseaseKey: "Tomato___Spider_mites Two-spotted_spider_mite",
    diseaseName: "Two-Spotted Spider Mite",
    cropName: "Tomato",
    category: "Pest",
    severity: "moderate",
    overview: "Two-spotted spider mites (Tetranychus urticae) are tiny arachnids that feed on plant cells, causing stippling and discoloration of leaves. They thrive in hot, dry conditions.",
    symptoms: ["Fine stippling or speckling on leaves", "Yellowing or bronzing of leaves", "Fine webbing on leaf undersides", "Leaf curling and drying", "Reduced plant vigor"],
    causes: ["Tetranychus urticae (two-spotted spider mite)", "Hot, dry conditions favoring mite populations", "Dusty conditions", "Use of broad-spectrum insecticides killing natural predators"],
    conditions: ["Hot temperatures above 30°C", "Low humidity", "Dusty environments", "Water-stressed plants", "Absence of natural predators"],
    prevention: ["Maintain adequate irrigation", "Avoid dusty conditions near fields", "Encourage natural predators", "Use selective pesticides", "Regular field scouting"],
    management: ["Introduce predatory mites", "Apply miticide if infestation is severe", "Increase humidity around plants", "Remove heavily infested leaves", "Use insecticidal soap or neem oil"],
    suggestedActions: ["Inspect plants thoroughly for mite activity", "Increase watering to reduce plant stress", "Introduce biological control agents", "Apply neem oil or insecticidal soap", "Remove heavily infested leaves"],
    isHealthy: false,
  },
  {
    diseaseKey: "Tomato___Target_Spot",
    diseaseName: "Target Spot",
    cropName: "Tomato",
    category: "Fungal",
    severity: "moderate",
    overview: "Target spot is caused by the fungus Corynespora cassiicola. It can affect leaves, stems, and fruits of tomato plants, causing significant yield losses in warm, humid regions.",
    symptoms: ["Brown lesions with concentric rings (target-like)", "Irregular-shaped spots", "Dark borders around lesions", "Premature defoliation", "Fruit lesions with dark centers"],
    causes: ["Corynespora cassiicola fungus", "Infected plant debris", "Seed-borne infection", "Wind and rain dispersal"],
    conditions: ["Warm temperatures (25-30°C)", "High humidity", "Extended wet periods", "Poor air circulation", "Dense planting"],
    prevention: ["Use certified disease-free seed", "Practice crop rotation", "Maintain proper plant spacing", "Remove crop debris", "Use resistant varieties when available"],
    management: ["Apply fungicide at first symptoms", "Remove severely affected leaves", "Improve air circulation", "Avoid overhead irrigation", "Monitor regularly"],
    suggestedActions: ["Remove affected leaves and improve spacing", "Apply appropriate fungicide", "Improve field drainage", "Practice crop rotation next season", "Monitor closely for further spread"],
    isHealthy: false,
  },
  {
    diseaseKey: "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    diseaseName: "Tomato Yellow Leaf Curl Virus",
    cropName: "Tomato",
    category: "Viral",
    severity: "high",
    overview: "Tomato Yellow Leaf Curl Virus (TYLCV) is a geminivirus transmitted by whiteflies. It is one of the most devastating tomato diseases worldwide, causing severe stunting and yield loss.",
    symptoms: ["Upward curling of leaves", "Yellowing of leaf margins", "Stunted growth", "Reduced fruit production", "Small, deformed fruits", "Flower drop"],
    causes: ["Tomato Yellow Leaf Curl Virus (TYLCV)", "Whitefly transmission (Bemisia tabaci)", "Infected transplants", "Infected weed hosts nearby"],
    conditions: ["Warm temperatures", "High whitefly populations", "Presence of virus reservoir plants", "Tropical and subtropical regions", "Year-round cultivation"],
    prevention: ["Use resistant varieties", "Control whitefly populations", "Use reflective mulches", "Remove infected plants immediately", "Use virus-free transplants", "Install insect-proof screens in greenhouses"],
    management: ["Remove and destroy infected plants", "Control whiteflies with insecticides or biological agents", "Use yellow sticky traps", "Plant resistant cultivars", "No chemical cure exists for the virus"],
    suggestedActions: ["Remove infected plants immediately to prevent spread", "Implement whitefly control measures", "Use reflective mulch to deter whiteflies", "Plant resistant varieties in next cycle", "Consult an agricultural expert for regional management strategies"],
    isHealthy: false,
  },
  {
    diseaseKey: "Tomato___Tomato_mosaic_virus",
    diseaseName: "Tomato Mosaic Virus",
    cropName: "Tomato",
    category: "Viral",
    severity: "high",
    overview: "Tomato mosaic virus (ToMV) is a highly contagious virus that affects tomatoes and other solanaceous plants. It spreads through mechanical contact, contaminated tools, and infected seeds.",
    symptoms: ["Mottled light and dark green on leaves", "Leaf curling and distortion", "Stunted growth", "Reduced fruit quality", "Internal browning of fruits", "Uneven fruit ripening"],
    causes: ["Tomato mosaic virus (ToMV)", "Contaminated seeds", "Mechanical transmission through tools and handling", "Infected plant debris", "Tobacco products containing the virus"],
    conditions: ["Handling plants after touching tobacco", "Contaminated tools and equipment", "Warm temperatures", "High plant density", "Poor sanitation"],
    prevention: ["Use certified virus-free seeds", "Disinfect tools regularly", "Wash hands before handling plants", "Do not use tobacco near plants", "Use resistant varieties", "Remove infected plants promptly"],
    management: ["Remove and destroy infected plants", "Disinfect all tools and equipment", "Practice strict hygiene", "Use milk solution to deactivate virus on tools", "No chemical treatment available"],
    suggestedActions: ["Remove infected plants immediately", "Disinfect all tools with 10% bleach solution", "Avoid smoking near plants", "Wash hands thoroughly before handling healthy plants", "Plant resistant varieties next season"],
    isHealthy: false,
  },
  {
    diseaseKey: "Tomato___Bacterial_spot",
    diseaseName: "Bacterial Spot",
    cropName: "Tomato",
    category: "Bacterial",
    severity: "moderate",
    overview: "Bacterial spot is caused by Xanthomonas species and affects leaves, stems, and fruits of tomatoes. It is a major disease in warm, humid growing regions.",
    symptoms: ["Small dark, water-soaked spots on leaves", "Spots may have yellow halos", "Scabby raised spots on fruits", "Leaf yellowing and defoliation", "Spots on stems and petioles"],
    causes: ["Xanthomonas euvesicatoria", "Xanthomonas perforans", "Contaminated seeds", "Infected transplants", "Rain splash dispersal"],
    conditions: ["Warm temperatures (25-30°C)", "High humidity and rainfall", "Overhead irrigation", "Windy conditions during rain", "Dense plant canopy"],
    prevention: ["Use disease-free seeds and transplants", "Practice crop rotation", "Avoid overhead irrigation", "Use copper-based sprays preventively", "Remove crop debris"],
    management: ["Apply copper and mancozeb fungicides", "Remove infected plant material", "Improve air circulation", "Reduce leaf wetness duration", "Use resistant varieties when available"],
    suggestedActions: ["Remove visibly infected leaves", "Apply copper-based bactericide", "Improve plant spacing", "Switch to drip irrigation", "Monitor and protect nearby healthy plants"],
    isHealthy: false,
  },
  // Potato diseases
  {
    diseaseKey: "Potato___healthy",
    diseaseName: "Healthy",
    cropName: "Potato",
    category: "Healthy",
    severity: "none",
    overview: "The potato plant appears healthy with no visible signs of disease or pest damage.",
    symptoms: ["Green, vigorous foliage", "Normal leaf shape", "No spots or lesions"],
    causes: [],
    conditions: [],
    prevention: ["Continue monitoring", "Maintain soil health", "Practice crop rotation"],
    management: ["Regular monitoring", "Proper fertilization"],
    suggestedActions: ["Continue current care practices"],
    isHealthy: true,
  },
  {
    diseaseKey: "Potato___Early_blight",
    diseaseName: "Early Blight",
    cropName: "Potato",
    category: "Fungal",
    severity: "moderate",
    overview: "Early blight in potatoes is caused by Alternaria solani. It produces characteristic target-like lesions on leaves and can reduce tuber yield and quality.",
    symptoms: ["Dark concentric ring spots on leaves", "Lower leaves affected first", "Yellowing around lesions", "Premature defoliation", "Tuber lesions near stem end"],
    causes: ["Alternaria solani fungus", "Infected crop debris", "Contaminated seed tubers"],
    conditions: ["Warm temperatures", "High humidity", "Alternating wet and dry periods", "Nutrient-deficient plants"],
    prevention: ["Use certified seed potatoes", "Practice 3-year crop rotation", "Maintain adequate plant nutrition", "Remove volunteer plants"],
    management: ["Apply fungicide preventively", "Remove infected foliage", "Ensure proper irrigation timing", "Harvest when vines are dead"],
    suggestedActions: ["Remove affected lower leaves", "Apply protective fungicide", "Improve plant nutrition", "Monitor for spread"],
    isHealthy: false,
  },
  {
    diseaseKey: "Potato___Late_blight",
    diseaseName: "Late Blight",
    cropName: "Potato",
    category: "Fungal",
    severity: "high",
    overview: "Late blight, caused by Phytophthora infestans, is the most destructive disease of potatoes. It can destroy entire fields within days under favorable conditions.",
    symptoms: ["Water-soaked dark lesions on leaves", "White sporulation on leaf undersides", "Rapid tissue death", "Brown, firm rot on tubers", "Foul smell from rotting tubers"],
    causes: ["Phytophthora infestans", "Infected seed tubers", "Infected plant debris", "Wind-dispersed spores"],
    conditions: ["Cool, moist conditions", "Temperatures 15-25°C", "High humidity above 90%", "Prolonged leaf wetness"],
    prevention: ["Use resistant varieties", "Destroy cull piles and volunteers", "Monitor weather conditions", "Apply preventive fungicide"],
    management: ["Apply fungicide at first forecast risk", "Destroy all infected material", "Harvest promptly when disease is present", "Ensure proper storage ventilation"],
    suggestedActions: ["Immediately remove and destroy infected plants", "Apply systemic fungicide to remaining crop", "Improve field drainage", "Consider early harvest to save tubers"],
    isHealthy: false,
  },
  // Corn/Maize diseases
  {
    diseaseKey: "Corn_(maize)___healthy",
    diseaseName: "Healthy",
    cropName: "Corn (Maize)",
    category: "Healthy",
    severity: "none",
    overview: "The corn plant shows no signs of disease, with healthy green leaves and normal growth patterns.",
    symptoms: ["Healthy green foliage", "Normal leaf development", "Vigorous growth"],
    causes: [],
    conditions: [],
    prevention: ["Regular field scouting", "Balanced fertilization", "Adequate irrigation"],
    management: ["Continue monitoring", "Maintain proper nutrition"],
    suggestedActions: ["Continue current management practices"],
    isHealthy: true,
  },
  {
    diseaseKey: "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    diseaseName: "Gray Leaf Spot",
    cropName: "Corn (Maize)",
    category: "Fungal",
    severity: "moderate",
    overview: "Gray leaf spot is caused by Cercospora zeae-maydis and is one of the most yield-limiting diseases of corn worldwide.",
    symptoms: ["Rectangular, tan-gray lesions", "Lesions parallel to leaf veins", "Yellowing around lesions", "Lesions merge in severe cases", "Premature leaf death"],
    causes: ["Cercospora zeae-maydis fungus", "Infected crop residue", "Wind and rain dispersal"],
    conditions: ["Warm, humid conditions", "Extended wet periods", "Minimum tillage fields", "Continuous corn production"],
    prevention: ["Practice crop rotation", "Use resistant hybrids", "Manage crop residue", "Ensure adequate fertilization"],
    management: ["Apply fungicide if disease is severe", "Rotate to non-host crops", "Consider tillage to bury residue"],
    suggestedActions: ["Assess disease severity and extent", "Consider fungicide application if widespread", "Plan crop rotation for next season", "Select resistant hybrids for future planting"],
    isHealthy: false,
  },
  {
    diseaseKey: "Corn_(maize)___Common_rust_",
    diseaseName: "Common Rust",
    cropName: "Corn (Maize)",
    category: "Fungal",
    severity: "low",
    overview: "Common rust of corn is caused by Puccinia sorghi. It produces characteristic cinnamon-brown pustules on leaves and is common but rarely causes significant yield loss.",
    symptoms: ["Small, circular to elongated cinnamon-brown pustules", "Pustules on both leaf surfaces", "Yellowing around pustules", "Chlorotic halos"],
    causes: ["Puccinia sorghi fungus", "Wind-blown spores from southern regions"],
    conditions: ["Cool, humid conditions", "Temperatures 16-22°C", "Extended dew periods"],
    prevention: ["Plant resistant hybrids", "Monitor fields regularly"],
    management: ["Usually not economically significant", "Apply fungicide only in severe cases", "Use resistant varieties"],
    suggestedActions: ["Monitor severity - usually self-limiting", "Apply fungicide only if severe and widespread", "Note resistant hybrid performance for future planting"],
    isHealthy: false,
  },
  {
    diseaseKey: "Corn_(maize)___Northern_Leaf_Blight",
    diseaseName: "Northern Leaf Blight",
    cropName: "Corn (Maize)",
    category: "Fungal",
    severity: "moderate",
    overview: "Northern corn leaf blight is caused by Exserohilum turcicum. It produces distinctive cigar-shaped lesions and can cause significant yield loss in susceptible hybrids.",
    symptoms: ["Long, elliptical gray-green lesions", "Cigar-shaped lesions 2-15 cm long", "Lesions parallel to leaf veins", "Tan to gray color when mature", "Premature leaf death"],
    causes: ["Exserohilum turcicum fungus", "Infected crop residue", "Wind-dispersed spores"],
    conditions: ["Moderate temperatures (18-27°C)", "High humidity", "Extended leaf wetness", "Continuous corn production"],
    prevention: ["Use resistant hybrids", "Practice crop rotation", "Manage crop residue", "Balanced fertilization"],
    management: ["Apply fungicide at VT-R1 stage if needed", "Rotate to reduce inoculum", "Use resistant hybrids in affected fields"],
    suggestedActions: ["Assess percent leaf area affected", "Apply fungicide if threshold exceeded", "Plan resistant hybrid selection for next season", "Implement crop rotation"],
    isHealthy: false,
  },
  // Apple diseases
  {
    diseaseKey: "Apple___healthy",
    diseaseName: "Healthy",
    cropName: "Apple",
    category: "Healthy",
    severity: "none",
    overview: "The apple tree foliage shows no signs of disease or pest damage.",
    symptoms: ["Green, vigorous leaves", "Normal leaf shape and size", "No visible spots or lesions"],
    causes: [],
    conditions: [],
    prevention: ["Regular pruning", "Proper orchard sanitation", "Balanced nutrition"],
    management: ["Continue monitoring", "Maintain cultural practices"],
    suggestedActions: ["Continue current orchard management"],
    isHealthy: true,
  },
  {
    diseaseKey: "Apple___Apple_scab",
    diseaseName: "Apple Scab",
    cropName: "Apple",
    category: "Fungal",
    severity: "moderate",
    overview: "Apple scab is caused by Venturia inaequalis and is the most common disease of apples worldwide. It affects leaves and fruit, reducing both yield and fruit quality.",
    symptoms: ["Olive-green to brown spots on leaves", "Dark, scabby lesions on fruit", "Leaf curling and drop", "Cracked, deformed fruit", "Velvety spots on young leaves"],
    causes: ["Venturia inaequalis fungus", "Overwintering in fallen leaves", "Spring spore dispersal by rain"],
    conditions: ["Cool, wet spring weather", "Rain during leaf emergence", "Prolonged wetness", "Temperatures 15-24°C"],
    prevention: ["Plant resistant varieties", "Rake and destroy fallen leaves", "Maintain tree spacing for air flow", "Apply preventive fungicide in spring"],
    management: ["Apply fungicide from bud break through petal fall", "Remove mummified fruit", "Prune for better air circulation", "Sanitation of fallen leaves"],
    suggestedActions: ["Remove and destroy fallen leaves", "Apply protective fungicide spray", "Improve air circulation through pruning", "Consider resistant varieties for new plantings"],
    isHealthy: false,
  },
  {
    diseaseKey: "Apple___Black_rot",
    diseaseName: "Black Rot",
    cropName: "Apple",
    category: "Fungal",
    severity: "moderate",
    overview: "Black rot is caused by Botryosphaeria obtusa and affects leaves, fruit, and limbs of apple trees. It produces distinctive frog-eye leaf spots and causes fruit rot.",
    symptoms: ["Frog-eye leaf spots (tan with purple margins)", "Large brown fruit rot", "Concentric rings on fruit", "Cankers on limbs", "Mummified fruit"],
    causes: ["Botryosphaeria obtusa fungus", "Infected mummified fruit", "Cankers on branches", "Wound entry points"],
    conditions: ["Warm, humid weather", "Wounds from insects or hail", "Weak or stressed trees", "Poor orchard sanitation"],
    prevention: ["Remove mummified fruit and dead wood", "Prune out cankers", "Maintain tree vigor", "Protect against wounds"],
    management: ["Prune dead and cankered wood", "Remove all mummified fruit", "Apply fungicide during growing season", "Maintain tree health"],
    suggestedActions: ["Prune out dead wood and cankers", "Remove all mummified fruit from tree and ground", "Apply fungicide if disease is prevalent", "Improve tree nutrition and vigor"],
    isHealthy: false,
  },
  {
    diseaseKey: "Apple___Cedar_apple_rust",
    diseaseName: "Cedar Apple Rust",
    cropName: "Apple",
    category: "Fungal",
    severity: "moderate",
    overview: "Cedar apple rust is caused by Gymnosporangium juniperi-virginianae and requires both apple and cedar (juniper) hosts to complete its life cycle.",
    symptoms: ["Bright yellow-orange spots on leaves", "Spots with red borders", "Tube-like structures on leaf undersides", "Premature leaf drop", "Fruit lesions"],
    causes: ["Gymnosporangium juniperi-virginianae fungus", "Nearby cedar/juniper trees", "Wind-dispersed spores"],
    conditions: ["Spring rain during apple bloom", "Presence of nearby juniper/cedar trees", "Cool, wet spring weather"],
    prevention: ["Remove nearby cedar/juniper trees within 2 miles", "Plant resistant apple varieties", "Apply preventive fungicide in spring"],
    management: ["Apply fungicide from pink bud through petal fall", "Remove galls from nearby junipers", "Use resistant cultivars"],
    suggestedActions: ["Apply fungicide at pink bud stage", "Consider removing nearby juniper/cedar trees", "Plan resistant variety replacement", "Monitor for secondary infections"],
    isHealthy: false,
  },
  // Grape diseases
  {
    diseaseKey: "Grape___healthy",
    diseaseName: "Healthy",
    cropName: "Grape",
    category: "Healthy",
    severity: "none",
    overview: "The grapevine shows no signs of disease with healthy foliage and normal growth.",
    symptoms: ["Healthy green leaves", "Normal canopy development", "No visible disease symptoms"],
    causes: [],
    conditions: [],
    prevention: ["Canopy management", "Regular monitoring", "Proper nutrition"],
    management: ["Continue good viticultural practices"],
    suggestedActions: ["Continue current vineyard management"],
    isHealthy: true,
  },
  {
    diseaseKey: "Grape___Black_rot",
    diseaseName: "Black Rot",
    cropName: "Grape",
    category: "Fungal",
    severity: "high",
    overview: "Black rot is caused by Guignardia bidwellii and is one of the most serious diseases of grapes in eastern North America. It can destroy entire clusters.",
    symptoms: ["Brown circular lesions on leaves with dark borders", "Black, shriveled berries (mummies)", "Reddish-brown spots on berries", "Berry rot with pycnidia visible", "Complete cluster destruction"],
    causes: ["Guignardia bidwellii fungus", "Overwintering mummies", "Infected canes and tendrils"],
    conditions: ["Warm, humid weather", "Rain during bloom and early fruit development", "Temperatures 20-27°C"],
    prevention: ["Remove mummified berries and infected wood", "Apply preventive fungicide", "Canopy management for air flow", "Remove wild grape hosts nearby"],
    management: ["Apply fungicide from shoot growth through véraison", "Remove all mummies and infected tissue", "Manage canopy for better spray coverage", "Sanitation is critical"],
    suggestedActions: ["Remove all mummified fruit from vines and ground", "Apply protective fungicide program", "Improve canopy management", "Prune infected canes"],
    isHealthy: false,
  },
  {
    diseaseKey: "Grape___Esca_(Black_Measles)",
    diseaseName: "Esca (Black Measles)",
    cropName: "Grape",
    category: "Fungal",
    severity: "high",
    overview: "Esca is a complex trunk disease caused by several fungi. It causes foliar symptoms and can lead to sudden vine death (apoplexy).",
    symptoms: ["Interveinal striping on leaves", "Brown-black spots between veins", "Tiger-stripe pattern on leaves", "Berry spotting (measles)", "Sudden vine collapse", "Internal wood staining"],
    causes: ["Phaeomoniella chlamydospora", "Phaeoacremonium species", "Fomitiporia mediterranea", "Wound infection from pruning"],
    conditions: ["Stressed vines", "Large pruning wounds", "Wet weather during dormancy", "Older vineyards"],
    prevention: ["Apply wound protectant after pruning", "Avoid large pruning wounds", "Maintain vine vigor", "Use clean planting material"],
    management: ["No effective chemical cure", "Re-trunk if partial infection", "Remove severely affected vines", "Apply biocontrol agents to wounds"],
    suggestedActions: ["Apply wound sealant to pruning cuts", "Assess internal wood staining", "Improve vine nutrition and water management", "Consult a viticulture specialist", "Consider re-training from healthy suckers"],
    isHealthy: false,
  },
  {
    diseaseKey: "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    diseaseName: "Leaf Blight (Isariopsis Leaf Spot)",
    cropName: "Grape",
    category: "Fungal",
    severity: "moderate",
    overview: "Leaf blight caused by Pseudocercospora vitis (formerly Isariopsis clavispora) affects grape foliage and can reduce photosynthesis and fruit quality.",
    symptoms: ["Dark brown to black spots on leaves", "Yellowing around spots", "Premature defoliation", "Reduced fruit quality", "Lesion enlargement over season"],
    causes: ["Pseudocercospora vitis fungus", "Infected leaf debris", "Rain splash dispersal"],
    conditions: ["Warm, humid conditions", "Poor air circulation", "Dense canopy", "Prolonged wet periods"],
    prevention: ["Canopy management for air flow", "Remove infected leaves", "Proper vine spacing", "Balanced nutrition"],
    management: ["Apply fungicide if severe", "Improve canopy management", "Remove infected tissue", "Ensure adequate nutrition"],
    suggestedActions: ["Remove affected leaves", "Improve canopy aeration", "Apply fungicide if disease is spreading", "Assess overall vine health and nutrition"],
    isHealthy: false,
  },
  // Generic healthy class for other crops
  {
    diseaseKey: "Background_without_leaves",
    diseaseName: "No Plant Detected",
    cropName: "Unknown",
    category: "Invalid",
    severity: "none",
    overview: "The uploaded image does not appear to contain a clear plant leaf. Please upload a close-up image of a plant leaf for analysis.",
    symptoms: ["No visible plant material", "Non-leaf image"],
    causes: [],
    conditions: [],
    prevention: ["Ensure the image is a close-up of a plant leaf", "Use good lighting", "Focus on the leaf surface"],
    management: ["Retake the photo focusing on a single leaf"],
    suggestedActions: ["Upload a new image showing a clear plant leaf", "Ensure good lighting and focus", "Center the leaf in the frame"],
    isHealthy: true,
  },
];

export function getDiseaseByKey(key: string): DiseaseInfo | undefined {
  return DISEASE_DATABASE.find((d) => d.diseaseKey === key);
}

export function getDiseasesByCrop(cropName: string): DiseaseInfo[] {
  return DISEASE_DATABASE.filter((d) => d.cropName === cropName);
}

export function getSupportedCrops(): string[] {
  const crops = new Set(DISEASE_DATABASE.filter(d => !d.isHealthy && d.category !== "Invalid").map((d) => d.cropName));
  return Array.from(crops).sort();
}

export function getCropDiseaseKeys(cropName: string): string[] {
  return DISEASE_DATABASE.filter((d) => d.cropName === cropName).map((d) => d.diseaseKey);
}

export const ALL_CLASS_LABELS = DISEASE_DATABASE.map((d) => d.diseaseKey);